version: '3'

services:
    db:
        image: postgres:12
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: hvuel
        ports:
            - 5432:5432
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - db_backend
    app:
        build: .
        ports:
            - 3000:8000
        networks:
            - db_backend

networks:
    db_backend: